# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: generate stealth.min.js

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.10.0]

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v3

      - name: Prepare Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Script
        run: |
          npx extract-stealth-evasions
          cp -f stealth.min.js /home/runner/work/slime/slime/slime-web/src/main/resources
          
      - name: Commit stealth.min.js
        uses: EndBug/add-and-commit@v4
        with:
          add: 'stealth.min.js'
          force: true
          ref: 'master'
          message: '🤖 auto-updated stealth.min.js with newest evasions'
        env:
          GITHUB_TOKEN: ${{ secrets.SLIME_TOKEN }}
